### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by christhirst** [christhirst/ldap#1]
- [ ] dart getall endpoint
- [ ] dart get by id endpoint
- [ ] dart delete endpoint
- [ ] dart patch endpoint
- [ ] dart replace endpoint
- [ ] go replace
- [ ] go patch
- [ ] config to jsonparsing
- [ ] central logging config
